spring.application.name=bff-scheduler

user.url=localhost:8080/usuario
task-scheduler.url=localhost:8081/tarefas
notification.url=localhost:8082/email

server.port=8083


cron.horario=0 0/5 * * * ? 

usuario.email=admin@admin.com  
usuario.senha=1234